/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Modelo.ModeloAgencia;
import java.io.File;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rodri
 */
public class Inicio extends javax.swing.JFrame {
        JFileChooser seleccionado = new JFileChooser();
        File archivo;
        ModeloAgencia g = new ModeloAgencia();
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        _VyH = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        _NombreC = new javax.swing.JTextField();
        _Dni = new javax.swing.JTextField();
        _Tlf = new javax.swing.JTextField();
        _CodSuc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        _NombreH = new javax.swing.JTextField();
        _NEstrellas = new javax.swing.JTextField();
        _Ciu = new javax.swing.JTextField();
        _Reg = new javax.swing.JTextField();
        _ClaseH = new javax.swing.JTextField();
        _CancelarH = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        _Tab_H = new javax.swing.JTable();
        _BuscarH = new javax.swing.JButton();
        _RervarH = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        _Compania = new javax.swing.JTextField();
        _Origen = new javax.swing.JTextField();
        _Destino = new javax.swing.JTextField();
        _FechaS = new javax.swing.JTextField();
        _FechaL = new javax.swing.JTextField();
        _BuscarV = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        _Tab_V = new javax.swing.JTable();
        _CancelarV = new javax.swing.JButton();
        _RervarV = new javax.swing.JButton();
        btnRegistros = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        _CodH = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        _CodV = new javax.swing.JTextField();
        Registros = new javax.swing.JPanel();
        btnAbrir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ventanaArchivo = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTableReservas = new javax.swing.JTable();
        btnMostrarRH = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnMostrarRV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.CardLayout());

        _VyH.setPreferredSize(new java.awt.Dimension(1300, 765));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel1.setText("Agencia");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Datos:");

        jLabel3.setText("Nombre: ");

        jLabel4.setText("Dni:");

        jLabel5.setText("Teléfono:");

        jLabel6.setText("Sucursal:");

        _NombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _NombreCActionPerformed(evt);
            }
        });

        _Dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _DniActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Hoteles:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Vuelos:");

        jLabel9.setText("Nombre:");

        jLabel10.setText("Ciudad:");

        jLabel11.setText("Nº Estrellas");

        jLabel12.setText("Regimen:");

        jLabel13.setText("Clse Habitación:");

        _CancelarH.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        _CancelarH.setText("Cancelar");

        _Tab_H.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        _Tab_H.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _Tab_HMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(_Tab_H);

        _BuscarH.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        _BuscarH.setText("Buscar");
        _BuscarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _BuscarHActionPerformed(evt);
            }
        });

        _RervarH.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        _RervarH.setText("Reservar");

        jLabel14.setText("Compania:");

        jLabel15.setText("Origen:");

        jLabel16.setText("Destino:");

        jLabel17.setText("Fecha de Salida:");

        jLabel18.setText("Fecha de Llegada:");

        _Destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _DestinoActionPerformed(evt);
            }
        });

        _BuscarV.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        _BuscarV.setText("Buscar");

        _Tab_V.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        _Tab_V.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _Tab_VMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(_Tab_V);

        _CancelarV.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        _CancelarV.setText("Cancelar");

        _RervarV.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        _RervarV.setText("Reservar");

        btnRegistros.setText("Registros");
        btnRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrosActionPerformed(evt);
            }
        });

        jLabel20.setText("CodHotel:");

        jLabel21.setText("CodVuelol:");

        javax.swing.GroupLayout _VyHLayout = new javax.swing.GroupLayout(_VyH);
        _VyH.setLayout(_VyHLayout);
        _VyHLayout.setHorizontalGroup(
            _VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_VyHLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(210, 210, 210)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistros)
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _VyHLayout.createSequentialGroup()
                .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, _VyHLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(_VyHLayout.createSequentialGroup()
                                .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(_NombreH)
                                    .addComponent(_Ciu, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(_VyHLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_CodH, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85)
                        .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(_VyHLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_NombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_Tlf, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_CodSuc, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(_VyHLayout.createSequentialGroup()
                                .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(_VyHLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(_ClaseH, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(_VyHLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(_Reg, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                                .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(_VyHLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(_VyHLayout.createSequentialGroup()
                                        .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, _VyHLayout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(_Origen))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, _VyHLayout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(_Compania, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(67, 67, 67)
                                        .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(_VyHLayout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(_FechaL, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(_VyHLayout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(_FechaS, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel8)
                                    .addGroup(_VyHLayout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(_CodV, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, _VyHLayout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(_BuscarH, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_BuscarV, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(_VyHLayout.createSequentialGroup()
                        .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(_VyHLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(_RervarH, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(182, 182, 182)
                                .addComponent(_CancelarH, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(_VyHLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _VyHLayout.createSequentialGroup()
                                .addComponent(_RervarV, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(149, 149, 149)
                                .addComponent(_CancelarV, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, _VyHLayout.createSequentialGroup()
                        .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, _VyHLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(_NEstrellas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, _VyHLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel7)))
                        .addGap(0, 996, Short.MAX_VALUE)))
                .addGap(115, 115, 115))
        );
        _VyHLayout.setVerticalGroup(
            _VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_VyHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnRegistros, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(_NombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_Dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_Tlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_CodSuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(_VyHLayout.createSequentialGroup()
                            .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(_CodH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel12)
                                .addComponent(_NombreH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(_Reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel13)
                                .addComponent(_Ciu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(_ClaseH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, _VyHLayout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17)
                                .addComponent(_FechaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(_FechaL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(_VyHLayout.createSequentialGroup()
                        .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(_CodV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(_Compania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(_Origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(_VyHLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(_NEstrellas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _VyHLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(_VyHLayout.createSequentialGroup()
                        .addComponent(_BuscarH, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _VyHLayout.createSequentialGroup()
                        .addComponent(_BuscarV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(_VyHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_RervarV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_CancelarV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_CancelarH, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_RervarH, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))))
        );

        jPanel1.add(_VyH, "card2");

        btnAbrir.setText("ABRIR ARCHIVO");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        ventanaArchivo.setColumns(20);
        ventanaArchivo.setRows(5);
        jScrollPane3.setViewportView(ventanaArchivo);

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("REGISTROS RESERVAS");

        JTableReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(JTableReservas);

        btnMostrarRH.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnMostrarRH.setText("Mostrar Reserva Hoteles");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnMostrarRV.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnMostrarRV.setText("Mostrar Reserva Vuelos");

        javax.swing.GroupLayout RegistrosLayout = new javax.swing.GroupLayout(Registros);
        Registros.setLayout(RegistrosLayout);
        RegistrosLayout.setHorizontalGroup(
            RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrosLayout.createSequentialGroup()
                .addContainerGap(724, Short.MAX_VALUE)
                .addGroup(RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrosLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrosLayout.createSequentialGroup()
                        .addComponent(btnMostrarRV)
                        .addGap(134, 134, 134)
                        .addComponent(btnMostrarRH)
                        .addGap(72, 72, 72))))
            .addGroup(RegistrosLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrosLayout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(RegistrosLayout.createSequentialGroup()
                        .addGroup(RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGuardar)
                            .addGroup(RegistrosLayout.createSequentialGroup()
                                .addComponent(btnAbrir)
                                .addGap(241, 241, 241))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        RegistrosLayout.setVerticalGroup(
            RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel19)
                .addGap(33, 33, 33)
                .addGroup(RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarRH)
                    .addComponent(btnMostrarRV))
                .addGap(1, 1, 1)
                .addComponent(btnAbrir)
                .addGap(18, 18, 18)
                .addGroup(RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrosLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(btnGuardar))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(38, 38, 38))
        );

        jPanel1.add(Registros, "card3");

        getContentPane().add(jPanel1, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _NombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__NombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__NombreCActionPerformed

    private void _DniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__DniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__DniActionPerformed

    private void _DestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__DestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__DestinoActionPerformed

    private void _BuscarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__BuscarHActionPerformed
        ModeloAgencia  cont = new ModeloAgencia();
        cont.listHoteles();
    }//GEN-LAST:event__BuscarHActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        if (seleccionado.showDialog(this, "ABRIR ARCHIVO")== JFileChooser.APPROVE_OPTION){
           archivo = seleccionado.getSelectedFile();
           if (archivo.canRead()){
            if (archivo.getName().endsWith("txt")){
                String contenido = g.AbrirTexto(archivo);
                ventanaArchivo.setText(contenido);
            }else {
                JOptionPane.showMessageDialog(null, "Por favor seleccione el archivo");
            }
        }
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrosActionPerformed
        jPanel1.removeAll();
        jPanel1.add(Registros);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_btnRegistrosActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
         jPanel1.removeAll();
        jPanel1.add(_VyH);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(seleccionado.showDialog(null, "GUARDAR") == JFileChooser.APPROVE_OPTION){
            archivo = seleccionado.getSelectedFile();
            if (archivo.getName().endsWith("txt")){
                String contenido = ventanaArchivo.getText();
                String respuesta = g.GuardarAtexto(archivo, contenido);
                if (respuesta != null){
                    JOptionPane.showMessageDialog(null, respuesta);
                }else {
                    JOptionPane.showMessageDialog(null, "Error al guardar texto");
                }
            }else {
                JOptionPane.showMessageDialog(null, "El texto se debe guardar en un formato de texto");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void _Tab_HMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__Tab_HMouseClicked
       DefaultTableModel modelT = (DefaultTableModel) _Tab_H.getModel();
       int selectedRowIndex = _Tab_H.getSelectedRow();
       
       _CodH.setText(modelT.getValueAt(selectedRowIndex, 0).toString());
       _NombreH.setText(modelT.getValueAt(selectedRowIndex, 1).toString());
       _Ciu.setText(modelT.getValueAt(selectedRowIndex, 2).toString());
       _NEstrellas.setText(modelT.getValueAt(selectedRowIndex, 3).toString());
       _Reg.setText(modelT.getValueAt(selectedRowIndex, 4).toString());
       _ClaseH.setText(modelT.getValueAt(selectedRowIndex, 5).toString());
    }//GEN-LAST:event__Tab_HMouseClicked

    private void _Tab_VMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__Tab_VMouseClicked
        DefaultTableModel modelT = (DefaultTableModel) _Tab_V.getModel();
       int selectedRowIndex = _Tab_V.getSelectedRow();
       
       _CodV.setText(modelT.getValueAt(selectedRowIndex, 0).toString());
       _Compania.setText(modelT.getValueAt(selectedRowIndex, 1).toString());
       _Origen.setText(modelT.getValueAt(selectedRowIndex, 2).toString());
       _Destino.setText(modelT.getValueAt(selectedRowIndex, 3).toString());
       _FechaS.setText(modelT.getValueAt(selectedRowIndex, 4).toString());
       _FechaL.setText(modelT.getValueAt(selectedRowIndex, 5).toString());
    }//GEN-LAST:event__Tab_VMouseClicked
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable JTableReservas;
    public javax.swing.JPanel Registros;
    public javax.swing.JButton _BuscarH;
    public javax.swing.JButton _BuscarV;
    public javax.swing.JButton _CancelarH;
    public javax.swing.JButton _CancelarV;
    public javax.swing.JTextField _Ciu;
    public javax.swing.JTextField _ClaseH;
    public javax.swing.JTextField _CodH;
    public javax.swing.JTextField _CodSuc;
    public javax.swing.JTextField _CodV;
    public javax.swing.JTextField _Compania;
    public javax.swing.JTextField _Destino;
    public javax.swing.JTextField _Dni;
    public javax.swing.JTextField _FechaL;
    public javax.swing.JTextField _FechaS;
    public javax.swing.JTextField _NEstrellas;
    public javax.swing.JTextField _NombreC;
    public javax.swing.JTextField _NombreH;
    public javax.swing.JTextField _Origen;
    public javax.swing.JTextField _Reg;
    public javax.swing.JButton _RervarH;
    public javax.swing.JButton _RervarV;
    public javax.swing.JTable _Tab_H;
    public javax.swing.JTable _Tab_V;
    public javax.swing.JTextField _Tlf;
    public javax.swing.JPanel _VyH;
    public javax.swing.JButton btnAbrir;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnMostrarRH;
    public javax.swing.JButton btnMostrarRV;
    public javax.swing.JButton btnRegistros;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTextArea ventanaArchivo;
    // End of variables declaration//GEN-END:variables
}
